- name: install packages
  become: yes
  apt: 
    name:
    - shairport-sync
    state: present
- name: "disable single shairport service"
  become: yes
  ignore_errors: yes
  systemd:
    name: "shairport-sync.service"
    state: stopped
    enabled: no
- name: remove user service entries
  become: yes
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "/usr/lib/systemd/system/shairport-sync.service"
    - "/etc/init.d/shairport-sync"
  notify: "reload systemd"
- name: configure shairport-sync
  become: yes
  template:
    src: "etc/default/shairport-sync.j2"
    dest: "/etc/default/shairport-sync"
  notify: "restart shairport"
- name: allow shairport to talk to pulse
  become: yes
  user:
    name: "shairport-sync"
    groups:
      - "pulse-access"
      - "audio"
- name: make shairport systemd worker
  become: yes
  copy:
    src: "etc/systemd/system/shairport-sync@.service"
    dest: "/etc/systemd/system/shairport-sync@.service"
  notify: "reload systemd"
- name: make shairport target item
  become: yes
  template:
    src: "etc/systemd/system/shairport-sync.target.j2"
    dest: "/etc/systemd/system/shairport-sync.target"
  notify: "reload systemd"
