- name: configure udev
  become: yes
  template:
    src: "etc/udev/rules.d/39-audio.rules.j2"
    dest: "/etc/udev/rules.d/39-audio.rules"
  notify: "reload udev rules"
- name: install packages
  become: yes
  apt: 
    name:
    - avahi-daemon
    - pulseaudio-module-zeroconf
    - pulsemixer
    - pulseaudio-utils
    state: present
- name: allow Ansible user access to audio
  become: yes
  user:
    name: "{{ansible_user}}"
    groups:
      - "pulse-access"
      - "pulse"
      - "audio"
    append: yes
- name: write asound conf
  become: yes
  template:
    src: "etc/asound.conf.j2"
    dest: "/etc/asound.conf"
  notify:
    - "reload alsa"
- name: write pulseaudio daemon.conf
  become: yes
  template:
    src: "etc/pulse/daemon.conf.j2"
    dest: "/etc/pulse/daemon.conf"
  notify: "restart pulseaudio"
- name: write pulseaudio client conf
  become: yes
  template:
    src: "etc/pulse/client.conf.j2"
    dest: "/etc/pulse/client.conf"
  notify: "restart shairport"
- name: set up DLNA renderer
  include_tasks:
    file: gmrender.yml
  when: audio.dlna
- name: bluetooth
  import_tasks: "bluetooth.yml"
  when: audio.bluetooth_rx or audio.bluetooth_tx
- name: write pulseaudio default.pa
  become: yes
  template:
    src: "etc/pulse/default.pa.j2"
    dest: "/etc/pulse/default.pa"
  notify: "restart pulseaudio"
- name: remove distro service entries
  become: yes
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "/usr/lib/systemd/user/pulseaudio.service"
    - "/usr/lib/systemd/user/pulseaudio.socket"
    - "/etc/systemd/user/default.target.wants/pulseaudio.service"
    - "/etc/systemd/user/sockets.target.wants/pulseaudio.socket"
  notify: "reload systemd"
- name: make pulseaudio systemd service
  become: yes
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
  loop:
    -  "etc/systemd/system/pulseaudio.service"
    -  "etc/systemd/system/pulseaudio.socket"
  notify: "reload systemd"
- name: set up airplay service
  include_tasks:
    file: airplay.yml
  when: audio.airplay
- meta: flush_handlers
- name: enable multi shairport
  become: yes
  systemd:
    name: "{{item}}"
    enabled: yes
    state: started
  loop:
    - "bluetooth.service"
    - "pulseaudio.service"
    - "shairport-sync.target"
