---
# configure this Armbian device to have a realtime kernel and various permissions.
- name: check for preempt kernel
  command:
    cmd: "uname -a"
  register: "unamea"
  changed_when: False
- assert:
    that:
      - "'PREEMPT' in unamea.stdout"
    fail_msg:
      "Realtime config requested but kernel is not preemptive."
- name: grant realtime permissions to audio group
  become: yes
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
  with_items:
    - "etc/security/limits.d/audio.conf"
  notify:
    - "reload systemd"
